
# Забираем базовые шаблоны для выкладки по SSH
include:
  - project: "libs/cicd-includes"
#     # Существуют заранее настроенные наборы задач для сборки и выкладки кода
#     # и frontend-а на Титан и хостинг для проектов с разной версией Node.js
#     # В ключе file, указанном ниже, можете написать один из следующих путей:
#     # "/templates/.base-tasks-node-8.yml"    -- для проектов с node.js 8-й версии
#     # "/templates/.base-tasks-node-10.yml"   -- для проектов с node.js 10-й версии
#     # "/templates/.base-tasks-node-14.yml"   -- для проектов с node.js 14-й версии
#     # "/templates/.base-tasks-node-16.yml"   -- для проектов с node.js 16-й версии
    file: "/testing/.base-tasks-node-18.yml"


# СБОРКА FRONTEND-А
# =================
build_frontend:
  extends: .task_frontend_build
  # В задаче доступны следующие переменные для переопределения:
  # variables:
  #   FRONTEND_PATH:  -- Путь к каталогу frontend от корня проекта (не сайта).
  #                   -- Начальный и конечный слэши указывать не надо!
  #                   -- По умолчанию настроен для проектов TAO: frontend
  #   BUILDS_PATH:    -- Путь к каталогу для сборок frontend-а от корня проекта (не сайта).
  #                   -- Начальный и конечный слэши указывать не надо!
  #                   -- По умолчанию настроен для проектов TAO: www/builds


# ВЫКЛАДКА КОДА НА ТИТАН
# ======================
deploy_titan:
  extends:
    - .task_code_deploy_titan
    - .mixin_php_8_1
  # В задаче доступны следующие переменные для переопределения:
  # variables:
  #   HOST_NAME:      -- Имя каталога сайта в каталоге site проекта на Титане.
  #                   -- По умолчанию берётся название репозитория.
  #                   -- Если каталог сайта на Титане называется иначе,
  #                   -- то его можно указать в этой переменной.
  #   SSH_KEY:        -- Приватный ключ для доступа к виртуальной машине проекта на Титане.
  #                   -- По умолчанию берётся ключ пользователя git, хранящийся в переменной
  #                   -- глобальных настроек CI/CD GitLab (на git.techart.ru).
  #                   -- Если возникает потребность замены, лучше так же сохранить его в переменную
  #                   -- CI/CD настроек проекта, а значение той переменной присваивать тут в SSH_KEY.
  #   TITAN_HOST:     -- Имя виртуальной машины проекта на Титане.
  #                   -- По умолчанию используется машина php74.vps.intranet .
  #                   -- Указывать точную машину не обязательно, но если потребуется, то это
  #                   -- можно сделать через переменную TITAN_HOST.
  #   TITAN_USER:     -- Имя пользователя для доступа на Титан.
  #                   -- По умолчанию используется пользователь git.
  #                   -- Менять пользователя без крайней нужды не рекомендуется, но если потребуется,
  #                   -- то обязательно следует заменить и SSH_KEY на приватный ключ указанного пользователя.


# ВЫКЛАДКА FRONTEND-А НА ТИТАН
# ============================
deploy_frontend_titan:
  extends:
    - .task_frontend_deploy_titan
    - .mixin_php_8_1
  # В задаче доступны следующие переменные для переопределения:
  # variables:
  #   HOST_NAME:      -- Имя каталога сайта в каталоге site проекта на Титане.
  #                   -- По умолчанию берётся название репозитория.
  #                   -- Если каталог сайта на Титане называется иначе,
  #                   -- то его можно указать в этой переменной.
  #   SSH_KEY:        -- Приватный ключ для доступа к виртуальной машине проекта на Титане.
  #                   -- По умолчанию берётся ключ пользователя git, хранящийся в переменной
  #                   -- глобальных настроек CI/CD GitLab (на git.techart.ru).
  #                   -- Если возникает потребность замены, лучше так же сохранить его в переменную
  #                   -- CI/CD настроек проекта, а значение той переменной присваивать тут в SSH_KEY.
  #   TITAN_HOST:     -- Имя виртуальной машины проекта на Титане.
  #                   -- По умолчанию используется машина php74.vps.intranet .
  #                   -- Указывать точную машину не обязательно, но если потребуется, то это
  #                   -- можно сделать через переменную TITAN_HOST.
  #   TITAN_USER:     -- Имя пользователя для доступа на Титан.
  #                   -- По умолчанию используется пользователь git.
  #                   -- Менять пользователя без крайней нужды не рекомендуется, но если потребуется,
  #                   -- то обязательно следует заменить и SSH_KEY на приватный ключ указанного пользователя.
  #   FRONTEND_PATH:  -- Путь к каталогу frontend от корня проекта (не сайта).
  #                   -- Начальный и конечный слэши указывать не надо!
  #                   -- По умолчанию настроен для проектов TAO: frontend
  #   BUILDS_PATH:    -- Путь к каталогу для сборок frontend-а от корня проекта (не сайта).
  #                   -- Начальный и конечный слэши указывать не надо!
  #                   -- По умолчанию настроен для проектов TAO: www/builds
  variables:
    TITAN_HOST: php81.vps.intranet


# ВЫКЛАДКА КОДА НА ХОСТИНГ
# ========================
deploy_hosting:
  extends:
    - .task_code_deploy_hosting
    - .mixin_php_8_1
  # В задаче доступны следующие переменные для переопределения:
  # variables:
  #   HOST_NAME:      -- Доменное имя сайта.
  #                   -- По умолчанию берётся название репозитория.
  #                   -- В приницпе, при выкладке на хостинг участвует только в стартовом сообщении.
  #   SSH_KEY:        -- Приватный ключ для доступа к хостингу проекта.
  #                   -- По умолчанию не указан.
  #                   -- Для доступа на хостинг по ключу лучше сохранить его в переменную CI/CD настроек
  #                   -- проекта, а значение той переменной присваивать тут в SSH_KEY.
  #   SSH_HOST:       -- Адрес машины хостинга сайта.
  #                   -- По умолчанию берётся название репозитория (как доменное имя).
  #                   -- Если адрес машины хостинга другой (например, известен только IP-адрес),
  #                   -- то его надо указать в переменной SSH_HOST.
  #   SSH_LOGIN:      -- Имя пользователя для доступа на машину хостинга сайта.
  #                   -- По умолчанию указано имя git.
  #                   -- Скорее всего, такого пользователя на машине хостинга нет, поэтому обязательно
  #                   -- укажите в этой переменной имя настоящего пользователя. Лучше всего, через переменную
  #                   -- в CI/CD настройках проекта.
  #   SSH_PASSWORD:   -- Пароль пользователя для доступа на машину хостинга сайта.
  #                   -- По умолчанию указана пустая строка.
  #                   -- Обязательно укажите пароль пользователя, если не используете доступ по ключу.
  #                   -- Указывайте пароль пользователя через переменную в CI/CD настройках проекта, и ставьте у
  #                   -- той переменной галочку "Mask variable", чтобы её значение не показывалось в журнале.
  #   SSH_PORT:       -- Порт для доступа на машину хостинга сайта.
  #                   -- По умолчанию указан стандартный порт 22.
  #                   -- Если на хостинге проекта используется нестандартный порт, то его следует
  #                   -- указать в переменной SSH_PORT.
  #   SITE_DIR:       -- Абсолютный адрес каталога проекта (git-репозитория) на машине хостинга сайта.
  #                   -- По умолчанию строится с использованием имени пользователя - /home/$SSH_LOGIN/site .
  #                   -- Если на машине хостинга проект располагается в каком-то другом каталоге, то его
  #                   -- следует указать в переменной SITE_DIR.
  variables:
    SSH_HOST: $HOSTING_SSH_HOST
    SSH_LOGIN: $HOSTING_SSH_LOGIN
    SSH_PASSWORD: $HOSTING_SSH_PASSWORD


# ВЫКЛАДКА FRONTEND-А НА ХОСТИНГ
# ==============================
deploy_frontend_hosting:
  extends:
    - .task_frontend_deploy_hosting
    - .mixin_php_8_1
  # В задаче доступны следующие переменные для переопределения:
  # variables:
  #   HOST_NAME:      -- Доменное имя сайта.
  #                   -- По умолчанию берётся название репозитория.
  #                   -- В приницпе, при выкладке на хостинг участвует только в стартовом сообщении.
  #   SSH_KEY:        -- Приватный ключ для доступа к хостингу проекта.
  #                   -- По умолчанию не указан.
  #                   -- Для доступа на хостинг по ключу лучше сохранить его в переменную CI/CD настроек
  #                   -- проекта, а значение той переменной присваивать тут в SSH_KEY.
  #   SSH_HOST:       -- Адрес машины хостинга сайта.
  #                   -- По умолчанию берётся название репозитория (как доменное имя).
  #                   -- Если адрес машины хостинга другой (например, известен только IP-адрес),
  #                   -- то его надо указать в переменной SSH_HOST.
  #   SSH_LOGIN:      -- Имя пользователя для доступа на машину хостинга сайта.
  #                   -- По умолчанию указано имя git.
  #                   -- Скорее всего, такого пользователя на машине хостинга нет, поэтому обязательно
  #                   -- укажите в этой переменной имя настоящего пользователя. Лучше всего, через переменную
  #                   -- в CI/CD настройках проекта.
  #   SSH_PASSWORD:   -- Пароль пользователя для доступа на машину хостинга сайта.
  #                   -- По умолчанию указана пустая строка.
  #                   -- Обязательно укажите пароль пользователя, если не используете доступ по ключу.
  #                   -- Указывайте пароль пользователя через переменную в CI/CD настройках проекта, и ставьте у
  #                   -- той переменной галочку "Mask variable", чтобы её значение не показывалось в журнале.
  #   SSH_PORT:       -- Порт для доступа на машину хостинга сайта.
  #                   -- По умолчанию указан стандартный порт 22.
  #                   -- Если на хостинге проекта используется нестандартный порт, то его следует
  #                   -- указать в переменной SSH_PORT.
  #   SITE_DIR:       -- Абсолютный адрес каталога проекта (git-репозитория) на машине хостинга сайта.
  #                   -- По умолчанию строится с использованием имени пользователя - /home/$SSH_LOGIN/site .
  #                   -- Если на машине хостинга проект располагается в каком-то другом каталоге, то его
  #                   -- следует указать в переменной SITE_DIR.
  #   FRONTEND_PATH:  -- Путь к каталогу frontend от корня проекта (не сайта).
  #                   -- Начальный и конечный слэши указывать не надо!
  #                   -- По умолчанию настроен для проектов TAO: frontend
  #   BUILDS_PATH:    -- Путь к каталогу для сборок frontend-а от корня проекта (не сайта).
  #                   -- Начальный и конечный слэши указывать не надо!
  #                   -- По умолчанию настроен для проектов TAO: www/builds
  variables:
    SSH_HOST: $HOSTING_SSH_HOST
    SSH_LOGIN: $HOSTING_SSH_LOGIN
    SSH_PASSWORD: $HOSTING_SSH_PASSWORD
